<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-05-16T10:05:03 BDT" name="Default suite" finished-at="2024-05-16T10:05:27 BDT" duration-ms="23886">
    <groups>
    </groups>
    <test started-at="2024-05-16T10:05:03 BDT" name="Default test" finished-at="2024-05-16T10:05:27 BDT" duration-ms="23886">
      <class name="test.com.Gmail_message_send">
        <test-method is-config="true" signature="setDriver()[pri:0, instance:test.com.Gmail_message_send@248e319b]" started-at="2024-05-16T10:04:55 BDT" name="setDriver" finished-at="2024-05-16T10:05:03 BDT" duration-ms="7464" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setDriver -->
        <test-method signature="gmail_signin()[pri:1, instance:test.com.Gmail_message_send@248e319b]" started-at="2024-05-16T10:05:03 BDT" name="gmail_signin" finished-at="2024-05-16T10:05:27 BDT" duration-ms="23818" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- gmail_signin -->
        <test-method signature="gmail_send_message()[pri:2, instance:test.com.Gmail_message_send@248e319b]" started-at="2024-05-16T10:05:27 BDT" name="gmail_send_message" finished-at="2024-05-16T10:05:27 BDT" duration-ms="6" status="FAIL">
          <exception class="java.lang.Error">
            <message>
              <![CDATA[Unresolved compilation problems: 
Unhandled exception type FindFailed
Unhandled exception type FindFailed
Unhandled exception type FindFailed
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Error: Unresolved compilation problems: 
Unhandled exception type FindFailed
Unhandled exception type FindFailed
Unhandled exception type FindFailed

at test.com.Gmail_message_send.gmail_send_message(Gmail_message_send.java:89)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Error -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- gmail_send_message -->
      </class> <!-- test.com.Gmail_message_send -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
